version: '3'

services:
  federated:
    container_name: federated
    image: myriadsocial/myriad-federated
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    ports:
      - 3002:3000
    networks:
      myriad:
        ipv4_address: 172.27.2.1
        aliases:
          - federated

networks:
  myriad:
    external: true
